### PR TITLE
Hello from the Krich Group at the University of Ottawa!

### PR DESCRIPTION
**Pull request by kwrobert**
Hi Phoebe, 

My name is Kyle Robertson, I'm a Masters student at the University of Ottawa. My adviser, Jacob Krich, mentioned that he met you at MRS, and that you've been working with S4 and RCWA. 

It's funny, I originally forked your repo when I started my work on this project because of the Python 3 support. Thanks for getting that working! 

My code is a bit messy right now, but I opened a pull request so you can take a look at it, see the diffs, and decide if it will be of any use to you. I'd be happy to chat and help where I can any time. You have my contact info now, so feel free to reach out! 

Best, 

Kyle

### CODE REVIEW

**Comment by phoebe-p** [comment]
Hi Kyle,
Great to hear from you so quickly, and I really appreciate you sharing your code, I think it will be really useful for me. I remember your username from the issues page of S4, but hadn't realised the connection obviously! I have been using a commercial RCWA software for MATLAB (GD-Calc) quite frequently, but was interested in S4 to try to integrate it with my group's Python package for solar cell simulation (http://www.solcore.solar/) hence why I needed the Python 3 compatibility (plus, S4 has some other advantages, mainly being able to deal with circles!). I mostly succeeded, but unfortunately it ended up being extremely slow, which limits the usability obviously. Having spoken to other people familiar with S4 (including Jacob earlier today) it's clear this isn't a fundamental issue with S4 but something to do with how I'm running it (probably to do with linear algebra or FFT libraries), so I will probably have some questions about that.

**Comment by kwrobert** [comment]
Cool!


I'd be happy to help with any Linux or OSX compilation and installation questions. I added a pretty heavy dependency to S4 ([boost c++ libraries](https://www.boost.org/)) to enable saving solutions for later reuse (which has been hugely useful for me), and it can make compilation a bit tricky sometimes. I modified the Makefile to automatically download the right version of Boost and link it into the compilation process, but please let me know if you run into any issues.


My familiarity with Windows is very limited, but I've had great success using the "Windows Subsystem for Linux" or virtual machines when collaborators want to compile and use my code on a Windows machine. If you're okay with using one of those tools, then from there it's the same as using a Linux machine and I can help with compilation/installation issues.


QUICK DISCLAIMER: There are some bugs in the code I haven't fixed yet that will generate incorrect results but will compile and run just fine (the worst kind of bugs). I haven't fixed them because I don't use the buggy parts of the code to generate the results I need. If you do end up using this code for anything, just let me know and I can either point out the bugs or finally get around to fixing them.


I'm familiar with Solcore, and I actually took a look at your implementation of an absorption calculation using RCWA/S4. I think I understand what you're doing there, and I might have some suggestions about how to make it faster (provided I actually do understand what you're doing), but I have few questions about what kind of systems you're modeling, what you're standards are for speed, etc. first. If you ever revisit that calculation, let me know and we can chat!

**Comment by phoebe-p** [comment]
I gave up trying to get S4 (and many other things) working on Windows a very long time ago and have an Ubuntu VM running on my work computer for that reason, so that should be fine! I will definitely revisit the S4 implementation for Solcore, though I'm not sure how soon - I would love to get your input when I do look at it again, because I'm sure my implementation is not the most efficient way possible (it was also the first thing I ever wrote in Python so I'm sure I'll cringe when I go back and look at it!). What we need for Solcore is depth-dependent absorption (and total reflection/transmission), though not resolved in the x and y directions (so just averaged over a unit cell).

**Comment by phoebe-p** [comment]
**Edit 2: never mind, I figured out I had to run 'make boost' after looking at the Makefile more carefully :)**


I have fallen at the first hurdle... When I run make S4_pyext, it gives the following error:

mkdir -p ./build
mkdir -p ./build/S4k
mkdir -p ./build/S4r
mkdir -p ./build/modules
g++ -c -Wall -O3 -msse3 -msse2 -msse -fPIC -Wall -I. -IS4 -IS4/RNP -IS4/kiss_fft  -I/home/pmp/S4_Kyle/S4/S4/include -L/home/pmp/S4_Kyle/S4/S4/lib/ -lboost_serialization -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_FFTW3  -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H -DHAVE_LIBCHOLMOD -I/usr/include/suitesparse S4/S4.cpp -o build/S4k/S4.o
S4/S4.cpp:51:39: fatal error: boost/serialization/nvp.hpp: No such file or directory
 #include <boost/serialization/nvp.hpp>
                                       ^
compilation terminated.
Makefile:233: recipe for target 'build/S4k/S4.o' failed
make: *** [build/S4k/S4.o] Error 1

Some quick investigation indicates that (as the error suggests) the boost stuff hasn't been downloaded into the target folder (which, as far as I understand the Makefile, is S4/S4/lib), in fact that folder doesn't seem to exist. Is there something else I need to do first?

Edit: I ran 'make' first, which successfully downloads boost.tar.gz, but doesn't seem to actually compile it

**Comment by kwrobert** [comment]
Yes! Sorry should have mentioned that. First run “make boost”, then run “make S4_pyext”

**Comment by phoebe-p** [comment]
The boost installation seems to run fine, and I believe I have installed the other libraries necessary (at least I don't get any errors relating to them), but when I run 'make S4_pyext', it hangs after running pip3 install --upgrade:

sh gensetup.py.sh ./build ./build/libS4.a "-lblas -llapack -lfftw3 -lpthread -lcholmod -lamd -lcolamd -lcamd -lccolamd  -L/home/pmp15/S4/S4/lib/ -lboost_serialization" /home/pmp15/S4/S4
LIBFILE: ./build/libS4.a
pip3 install --upgrade ./
Processing /home/pmp15/S4

So it hangs on the 'Processing'  step. It has created a setup.py file, when I run that manually with python3 setup.py install it seems to work but when actually trying to use S4 it gives an error. Any thoughts?

**Comment by kwrobert** [comment]
Hmm, it's tough to say. Could you either paste in or upload a text file with the entire error message? If you are installing S4 globally, you will need root permissions to run the installation. Do you use virtual environments at all?

**Comment by kwrobert** [comment]
If you're willing, we could screen share via Skype or Teamviewer and debug this together. That's how I've successfully gotten others set up in the past (things are just generally easier and quicker that way).

**Comment by phoebe-p** [comment]
S4 seems to install ok, and I can do things like 'import S4' and S = S4.New(.....), but as soon as I try to run anything which requires solving anything I get the dreaded 'Segmentation fault (core dumped)'. However, I am just trying to run it in the Ubuntu subsystem for windows (which is just a bash window) on my laptop so I wonder if it's some type of issue to do with memory allocation. I will try again with my work computer when I'm back in the UK and if the issue persists it would be great if we could try to debug together via screen sharing, I'll let you know!

**Comment by kwrobert** [comment]
That might be due to one of the bugs I mentioned earlier. You need to pass the right set of configuration options to the solver using the SetOptions function to avoid the buggy parts of the code, but we'll see how things work out when you return to the UK.

**Comment by phoebe-p** [comment]
Hi Kyle! Would you be able to do a Skype call some afternoon (for me, so morning for you) this week? Any day except Tuesday should work for me! (my email is phoebe.pearce15 [at] imperial.ac.uk)

**Pull request merged**
